/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stylized_clouds/scene.gltf --transform --aggresive 
Files: stylized_clouds/scene.gltf [5.22KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [813.6KB] (-15486%)
Author: lavakongen (https://sketchfab.com/lavakongen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-clouds-e326c36890364526910cba03c1393ebc
Title: Stylized clouds
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function CloudScene(props) {
  const { nodes, materials } = useGLTF("/clouds.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.base1}
        scale={0.036}
      />
    </group>
  )
}

useGLTF.preload("/clouds.glb")
