/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 green_planet/scene.gltf --transform --aggresive 
Files: green_planet/scene.gltf [17.54KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [1MB] (-5614%)
Author: jimmyn64 (https://sketchfab.com/jimmyn64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-planet-965dcf47e69e4c139741598162b147cf
Title: Green Planet
*/

import React from "react"
import { useGraph, useFrame } from "@react-three/fiber"
import { useGLTF, useAnimations } from "@react-three/drei"
import { SkeletonUtils } from "three-stdlib"

export function GreenPlanetScene(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF("/green-planet.glb")
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useFrame(() => {
    group.current.rotation.y += props.rotateSpeed
  })
  return (
    <group
      position={[10, 6.5, 0]}
      ref={group}
      {...props}
      dispose={null}
      scale={props.scale}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <mesh
          name="QonoS_Atmosphere_Atmosphere_0"
          geometry={nodes.QonoS_Atmosphere_Atmosphere_0.geometry}
          material={materials.Atmosphere}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={116.459}
        />
        <skinnedMesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.Ground}
          skeleton={nodes.Object_12.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={109.98}
        />
        <skinnedMesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={materials.Clouds}
          skeleton={nodes.Object_14.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={109.98}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/green-planet.glb")
