/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kepler-452b/scene.gltf --transform --aggresive 
Files: kepler-452b/scene.gltf [8.45KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [406.11KB] (-4706%)
Author: Yo.Ri (https://sketchfab.com/grox777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kepler-452b-816d14fb09974160aed7cb264bd770bc
Title: Kepler-452b
*/

import React from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export function KeplerScene(props) {
  const group = React.useRef()

  const { nodes, materials } = useGLTF("/kepler-452b.glb")
  useFrame(() => {
    group.current.rotation.y += props.rotateSpeed
  })
  return (
    <group
      position={[13, 8, 0]}
      ref={group}
      {...props}
      dispose={null}
      scale={props.scale}
    >
      <mesh
        geometry={nodes["����������001_CLOUDS_0"].geometry}
        material={materials.CLOUDS}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={103.649}
      />
      <mesh
        geometry={nodes["����������_Kepler_0"].geometry}
        material={materials.Kepler}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload("/kepler-452b.glb")
