/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mars_gltf/scene.gltf --transform --aggresive 
Files: mars_gltf/scene.gltf [4.47KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [447.48KB] (-9911%)
*/

import React from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export function MarsScene(props) {
  const group = React.useRef()

  const { nodes, materials } = useGLTF("/mars.glb")
  useFrame(() => {
    group.current.rotation.y += props.rotateSpeed
  })

  return (
    <group
      position={[0, 1, 0]}
      ref={group}
      {...props}
      dispose={null}
      scale={props.scale}
    >
      <mesh
        geometry={nodes.Earth_Planet_0.geometry}
        material={materials.Planet}
      />
    </group>
  )
}

useGLTF.preload("/mars.glb")
