/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 odious/scene.gltf --transform 
Files: odious/scene.gltf [6.05KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [279.68KB] (-4523%)
Author: IgorLugosi (https://sketchfab.com/igorlugosi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/odious-d2580bf2f3a3406a8e7567214c9a0725
Title: Odious
*/

import { useRef, useState, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { useRouter } from "next/navigation"
import { PLANET_LABELS } from "../utils/consts"
export function OdiousScene(props) {
  const group = useRef()
  const router = useRouter()
  const { nodes, materials } = useGLTF("/odious.glb")
  const [hovered, setHover] = useState(false)
  useFrame(() => {
    group.current.rotation.y += props.rotateSpeed
  })
  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto"
    props.setPlanetLabel
      ? props.setPlanetLabel(hovered ? PLANET_LABELS[2] : PLANET_LABELS[0])
      : null
    return () => (document.body.style.cursor = "auto")
  }, [hovered])

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={hovered && props.landing ? 1.5 : props.scale}
    >
      <mesh
        onClick={() => router.push("/squirrel")}
        onPointerOver={(e) => (e.stopPropagation(), setHover(true))}
        onPointerOut={(e) => setHover(false)}
        geometry={nodes.Sphere.geometry}
        material={materials.SurfaceMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.RingMaterial}
        rotation={[-Math.PI / 2, -0.2, 0]}
        scale={[5.892, 5.892, 6]}
      />
    </group>
  )
}

useGLTF.preload("/odious.glb")
