/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 odious/scene.gltf --transform 
Files: odious/scene.gltf [6.05KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [279.68KB] (-4523%)
Author: IgorLugosi (https://sketchfab.com/igorlugosi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/odious-d2580bf2f3a3406a8e7567214c9a0725
Title: Odious
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.SurfaceMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.RingMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.892, 5.892, 6]}
      />
    </group>
  )
}

useGLTF.preload("/scene-transformed.glb")
