/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 purple_planet/scene.gltf --transform 
Files: purple_planet/scene.gltf [11.44KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [541.68KB] (-4635%)
Author: Yo.Ri (https://sketchfab.com/grox777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purple-planet-264eb22207184fc99a5e3b1279a763b8
Title: Purple Planet
*/

import React from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame, useLoader } from "@react-three/fiber"
export function PurplePlanetScene(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF("/purple-planet.glb")
  const { actions } = useAnimations(animations, group)
  // useFrame(() => {
  //   group.current.rotation.y += props.rotateSpeed
  // })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Root"
          position={[-8, -3, 0]}
          rotation={[-Math.PI / 2, 0.2, 0]}
          scale={props.scale}
        >
          <group name="Planet" rotation={[0, 0, Math.PI / 2]}>
            <group
              name="Clouds_0"
              rotation={[0, 0, -Math.PI / 2]}
              scale={1.013}
            >
              <mesh
                name="Clouds_0_0"
                geometry={nodes.Clouds_0_0.geometry}
                material={materials.Clouds_0}
              />
            </group>
            <mesh
              name="Planet_0"
              geometry={nodes.Planet_0.geometry}
              material={materials.PurplePlanet}
              // rotateY={Math.PI / 2}
            />
          </group>
          <group name="Clouds_1" scale={1.019}>
            <mesh
              name="Clouds_1_0"
              geometry={nodes.Clouds_1_0.geometry}
              material={materials.Clouds_1}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/purple-planet.glb")
