/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ringed_gas_giant_planet/scene.gltf --transform --aggresive 
Files: ringed_gas_giant_planet/scene.gltf [6.57KB] > /Users/jpdephillips/Downloads/scene-transformed.glb [99.27KB] (-1411%)
Author: berzerkey (https://sketchfab.com/berzerkey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ringed-gas-giant-planet-b4e21775e84e4cf3890f7796cfab1aca
Title: Ringed Gas Giant Planet
*/

import { useRef, useState, useEffect } from "react"
import { useGLTF } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import { useRouter } from "next/navigation"
import { PLANET_LABELS } from "../utils/consts"

export function RingedGasGiantScene(props) {
  const group = useRef()
  const router = useRouter()
  const [hovered, setHover] = useState(false)

  const { nodes, materials } = useGLTF("/ringed-gas-giant.glb")
  useFrame(() => {
    group.current.rotation.y += props.rotateSpeed
  })
  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto"
    props.setPlanetLabel
      ? props.setPlanetLabel(hovered ? PLANET_LABELS[4] : PLANET_LABELS[0])
      : null
    return () => (document.body.style.cursor = "auto")
  }, [hovered])

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={hovered && props.landing ? 0.4 : props.scale}
    >
      <mesh
        onClick={() => router.push("/lexx")}
        onPointerOver={(e) => (e.stopPropagation(), setHover(true))}
        onPointerOut={(e) => setHover(false)}
        geometry={nodes.Cube_m_planet_0.geometry}
        material={materials.m_planet}
        rotation={[-1.944, -0.197, -0.076]}
        scale={5.881}
      />
      <mesh
        geometry={nodes.Plane_m_ring_0.geometry}
        material={materials.m_ring}
        rotation={[-1.944, -0.197, -0.076]}
        scale={10.394}
      />
    </group>
  )
}

useGLTF.preload("/ringed-gas-giant.glb")
